### ISSUE TITLE
Research styleguide and structure

### ISSUE THREAD

**Issue by MVucina** [chmjs/vue-cli-plugin-nsoft#2]
This task will include research of  :
 
- Routing and State Structure
- Directory Structure
- Component Styleguide

**Comment by DinkoMiletic** [comment]
https://docs.google.com/document/d/1nCHaUaee4Ud2YunLwvqUCUPfr0jAbVX8PxOg7ElSLio/edit#

**Comment by manico** [comment]
Recommended:

- `src` for source
- `src/mixins` for vue mixins
- `src/utility` for unitlity functions consumed by mixins and others 
- `src/api` for external communication
- `src/store` for store broken into modules
- `src/router` for store broken into modules
- `src/pages` for vue component pages
- `src/components` for vue components
- `src/layout` for vue component template pages
- `src/main.js` entrypoint for apps
- `src/index.js` entrypoint for libs

**Comment by aldinezi** [comment]
Even though it's not our practice to put various static and config files inside the `src` folder, should we consider placing those inside the `src` folder or define exact structure where those files should be kept in our projects?

**Comment by manico** [comment]
@aldinezi I think config should be outside src folder.
@MVucina Abstraction seems a good candidate for utility?

**Comment by MVucina** [comment]
Utility should be fine, `services` is more angular style

**Comment by aldinezi** [comment]
@manico & @MVucina I did not suggest placing `config` inside our source folder, but to consider if this issue related to folder structure should also cover the placement of such folders.

**Comment by MVucina** [comment]
This issue is more related to `src/` folder structure,  issue related to configuration stuff will cover placement of such folders

**Comment by MVucina** [comment]
I will just mention `static` folder which should be defined outside of `src`.

**Comment by MVucina** [comment]
**Folder structure:**
   _src/_
       `api/ `- abstraction for  external communication
       `assets/` - module assets (processed by module bundler)
       `components/ `- all components that are not main view in flat structure
       `directives/ `- all directives in flat structure
       `filters/` - all filters in flat structure
       `mixins/` - all mixins in flat structure
       `plugins/` - for plugins inclusion
       `utility/` - helper functions in flat structure
       `pages/` - component pages
       `layouts/` - component template pages
       `store/` - store stuff 
       `router/` -  routing stuff 
       `main.js` -  app entry file
       `App.vue` -  main app component

**Router structure:**
       `index.js `- app routes
       `{pageRouter}.js` - nested routes can be defined in separated file with appropriate name
       `navigatonGuards.js`- definition of global guards

**Store structure:**
      `state.js `- state tree
      `getters.js` - all getters
      `mutations.js`- all mutations
      `actions.js`- all actions
      `plugins/`- plugins in flat structure
      `modules/`- keep modules with appropriate named folders with same structure of files 
      `index.js`- where we assemble modules and export the store

**Note:** `static/` is outside of `src/` folder, keep static assets that are directly copied there

**Component styleguide:** Follow vue official [styleguide](https://vuejs.org/v2/style-guide/#Priority-B-Rules-Strongly-Recommended-Improving-Readability)

**Comment by manico** [comment]
Add `mutationTypes.js` for mutation enumeration in store.

**Comment by DinkoMiletic** [comment]
What about name-spacing modules?

**Comment by DinkoMiletic** [comment]
Change `static` to `public`.
