### ISSUE TITLE
[DISCUSSION] Adding gravity gateway as dependency

### ISSUE THREAD

**Issue by DinkoMiletic** [chmjs/vue-cli-plugin-nsoft#20]
Gravity gateway is most used cross team in-house dependency so let's discuss ideas.

We are sure about those two points:

1. We will prompt user with question does he want gateway as dependency
2. If yes, add dependency to `package.json`

Now, do you think that we can utilize Vue plugin to add boost productivity or to make DEV use best practice.. For example do you think that it would be good to expose gateway globally:

```lang=js
var gatewayMixin = {
  data: function () {
    return {
      slave: {...},
      master: {...}
    }
  }
}

new Vue({
  mixins: [gatewayMixin],
  created: function () {
    console.log(this.$gateway)
    // => { slave: {...}, master: {...} }
  }
})
```

**Comment by manico** [comment]
Vue goes agains this pattern for third-party components.
But, since we are not creating this cli plugin for the world, it is not a bad idea.

**Comment by kovacevjosip** [comment]
Maybe it would be better to add gravity gateway as service, so it can be used in actions or mutations.
If user select yes for gravity, it would make simple service:
```javascript
import Gateway from '@nsoft/seven-gravity-gateway/slave';

let gateway;
export default {
  init() {
    return new Promise((resolve) => {
      gateway = Gateway({
        debug: true,
        slaveId: 'SlaveId',
        load: (msg) => {
          resolve(msg.data);
        },
      });
    });
  },
  sendMessage(msg) {
    if (gateway) {
      gateway.sendMessage({ action: msg.action, data: msg.data });
    }
  },
};
```

How to use it inside component or actions:
```javascript
import gravityGateway from '@/services/gravityGateway';

...
mounted() {
  gravityGateway.init().then((data) => {

  });
}
```

This is just simple example that we used in one of our projects. 
If this is better approach, we could discuss some default template with basic options.

**Comment by DinkoMiletic** [comment]
So something like this:

1. create two files in utility folder, `gateway_slave.js` and `gateway_master.js`
2. content of slave

```js
import Gateway from '@nsoft/seven-gravity-gateway/slave';
let gateway;
export default {
  init(config) {
   // more work to do, probably merge config with load event so we can do resolve...
    return new Promise((resolve) => {
      gateway = Gateway(config);
    });
  },
  getInstance() {
   return gateway;
  },
};
```
3. content of master
```js
import Gateway from '@nsoft/seven-gravity-gateway/master';
let gateway;
export default {
  init(config) {
    return new Promise((resolve) => {
      gateway = Gateway(config);
    });
  },
  getInstance() {
   return gateway;
  },
};
```

**Comment by manico** [comment]
Just follow standards in naming and instead of `gateway_slave.js` create `gatewaySlave.js`. :p
Anyway, I would create just single file in utility called `gateway` with separation inside on slave and master.
