### ISSUE TITLE
Run Fails on Fresh Install

### ISSUE THREAD

**Issue by manico** [chmjs/vue-cli-plugin-nsoft#21]
After adding plugin and running `npm run serve` it fails with error:

`@vue/cli-plugin-e2e-nightwatch missing`

It seems that `npm install` is not run on plugin add?

Also, we get a lot of lint errors on `npm run lint`. It seems that test coverage files and node modules are not ignored? To reproduce run unit tests and then lint.

**Comment by kovacevjosip** [comment]
Only thing that is issue for me are lint errors. They are related with `coverage` folder in tests. Folder is made with `npm run test:unit` so we probably should ignore it.
Easiest solution would be to use `.eslintignore` file (it can be just copy of `.gitignore`).

- OS: Ubuntu 18.04
- node: v10.15.0
- npm: v6.4.1
- vue-cli: v3.3.0

PS: `npm run lint` autofixes `.eslintrc.js` (double quote string to single quote).

**Comment by MVucina** [comment]
`.eslintignore` file is added 

@manico i'm not able to reproduce issue you reported :thinking:

**Comment by manico** [comment]
Not sure what happened. :)
