### ISSUE TITLE
[DISCUSSION] Update editorconfig file

### ISSUE THREAD

**Issue by kovacevjosip** [chmjs/vue-cli-plugin-nsoft#22]
When initialize project via nsoft plugin and add some `scss` file (or any other file that has different extension from `*{js,jsx,ts,tsx,vue}`), indent size of that file will be editors default (mostly 4 spaces). Maybe it would be nice to update `.editorconfig` to use same indent style and size on all files.

Example ([reference](https://github.com/google/web-starter-kit/blob/master/.editorconfig)):
```.editorconfig
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
max_line_length = 100

[*.md]
trim_trailing_whitespace = false
```

One new line is added on reference example and that is `max_line_length = 100`.

**Comment by MVucina** [comment]
This is ok .. you can create PR
