### ISSUE TITLE
Research Styleguides

### ISSUE THREAD

**Issue by DinkoMiletic** [chmjs/vue-cli-plugin-nsoft#7]
- Format and Linting Styleguide
 - Config files separate or in package.json (eslint, jest, babel ...)
 - File naming
 - Project naming

**Comment by pandzicivan** [comment]
**Linting**

Linters available:

- JSLint
- JSHint
- ESLint

JSLint

- Not configurable
- Licence Shenanigans
- Smaller community
- Pretty Strict - Crockford’s recommendation of style linting

JSHint

- JSLint with configuration

ESLint

- Option to disable rules on individual lines
- 5 x downloads comparing with JSHint

ESLint

Most popular lint configurations are:
- Google
- Airbnb
- Standard	

Common for all 3:

- 2 space indent
- no trailing spaces
- single commas
- const over var


  | Google | Airbnb | Standard
-- | -- | -- | --
Semicolon Required | Y | Y | N
Trailing Commas | Y | Y | N
Space before function parentheses | N | N | Y
Console Statement Allowed | N | N | N
Object Curly Spacing | N | Y | N - Consistent
Array Bracket Spacing | N | N | N

Google and Airbnb are pretty strict with some minor differences. I believe that standard is a bit loose for our needs.

One thing which bothers me is the use of const over var(let) when variable reference won’t change. According to ES definition of const:

**It does NOT define a constant value. It defines a constant reference to a value.**

Doing this:
```lang=javascript
const payload = {
  temp: 12
};
payload.temp = 16;
```

...is perfectly valid JS but IMO it looks odd, especially for non-JS devs. 

Airbnb would be my choice but with disabled `prefer-const` rule. What are your opinions? 

Also there is lot of hype with Prettier which handles the code formatting and leaves the syntax errors to linting tools. I'll write update soon about its usage.

**Comment by DinkoMiletic** [comment]
I would go with Prettier

**Comment by manico** [comment]
So we go with `airbnb` configuration. Please add all recommended exceptions for config.

**Comment by pandzicivan** [comment]
Yeah, I know, it is subjective, but in linked post first paragraph states some contradictory stuff::

> It tells others reading your code that you don't intend the value to change.

But you do change the value, just not the reference 🤷‍♂️ 

You got the point regarding the optimizations, just right now there aren't any...
I would like to hear other opinions, like you said this is mainly subjective...
